name: clean_arch_task
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_svg: ^2.2.1
  go_router: ^16.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/NewRocker/NewRocker-Regular.ttf
    - assets/fonts/Raleway/Raleway-Bold.ttf
    - assets/fonts/Raleway/Raleway-Medium.ttf
    - assets/fonts/Raleway/Raleway-Regular.ttf
    - assets/fonts/Raleway/Raleway-SemiBold.ttf

  fonts:
    - family: NewRocker
      fonts:
        - asset: assets/fonts/NewRocker/NewRocker-Regular.ttf
          weight: 400

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700

# مولد الأصول (لو بتستخدم flutter_assets_generator أو حاجة مشابهة)
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: app_assets.dart
